### ISSUE TITLE
Documentation: needs explanation of how to install

### ISSUE THREAD

**Issue by WarthogARJ** [retorquere/zotero-auto-index#21]
Documentation does not explain much.
Most other Zotero plugins contain an xpi file, that you can use with the Zotero/Adds function.

As requested, I'm trying to install the lastest issue: 5.0.6

**Comment by retorquere** [comment]
The main page of this repo says

> Now compatible with Zotero 5. Install by downloading the [latest version](https://github.com/retorquere/zotero-auto-index/releases/latest)

That page has a download link for the xpi.
