### ISSUE TITLE
instulation problems

### ISSUE THREAD

**Issue by Maymiel** [retorquere/zotero-auto-index#33]
Hi, i a beginner, trying to install AutoGPT. 
i worked step by step with ChatGPT4, at the end we got stuck hear...
C:\Users\May\Google Drive\Auto-GPT-0.2.1>python main.py
Traceback (most recent call last):
  File "C:\Users\May\Google Drive\Auto-GPT-0.2.1\main.py", line 1, in <module>
    from autogpt import main
ImportError: cannot import name 'main' from 'autogpt' (C:\Users\May\Google Drive\Auto-GPT-0.2.1\autogpt\__init__.py)
 i tried insulting and uninstalling again - didnt help. i checked the python version it Python 3.11.3
 can you help?

**Comment by retorquere** [comment]
I think you're in the wrong repo
