### ISSUE TITLE
FF requires signing in

### ISSUE THREAD

**Issue by lizzydoodle** [retorquere/zotero-auto-index#5]
The new version of FF (48.0) refuses to allow to load plug-ins that are not verified. For me, Zotero Auto Index 0.0.36 is not loading anymore.

FF requests that developers allow the signing here
https://developer.mozilla.org/en-US/Add-ons/Distribution.

Thanks for looking into this!

**Comment by retorquere** [comment]
You'll have to uninstall the old version and install this version instead: https://github.com/retorquere/zotero-auto-index/releases/tag/0.0.37 . After that, it will auto-update.

**Comment by lizzydoodle** [comment]
Thank you!
