### ISSUE TITLE
Zotero quick search field does not change due to Zotero Auto Index

### ISSUE THREAD

**Issue by awesomeindustries** [retorquere/zotero-auto-index#7]
Hi, I have found a bug which appears to be caused by this plugin.

`Zotero Standalone 4.0.29.5 on OS X 10.11.6`

> in the quick search bar the search scope does not change after using the pull-down menu.
> Whenever I select "Title, Creator, Year", "All Fields & Tags", or "Everything", the input field keeps reading "Title, Creator, Year". However, the search works as selected using the pull-down menu. 

[Original topic in Zotero forums](https://forums.zotero.org/discussion/comment/262276)

**Comment by retorquere** [comment]
Can you go into `Preferences`->`Advanced`->`View Output` and paste the results here? I don't have access to the uploaded logs behind the report ID.

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-auto-index/releases/download/builds/zotero-auto-index-0.0.38-circle-8.xpi ? I have no errors in the logs, but the behavior is back to normal after the changes I made in this test version, I'd like to see if it works for you too. No idea what actually causes this problem, but the different way of getting the prefs seems to work.

**Comment by awesomeindustries** [comment]
Hi Emiliano, sorry for the late response. I've tried your new version and the problem is gone! Do you still want to take a look at the logs?

**Comment by retorquere** [comment]
Nope, the logs probably won't say anything (they didn't for me), so I'll just cut a new release.
