### ISSUE TITLE
Incompatible with Zotero 5

### ISSUE THREAD

**Issue by jolars** [retorquere/zotero-auto-index#8]
Auto Index is currently incompatible with Zotero 5. Are there any plans to update the plugin?

**Comment by retorquere** [comment]
Plans, yes, after [BBT](https://github.com/retorquere/zotero-better-bibtex/issues/555) is done.

**Comment by BenjaminHCCarr** [comment]
Wondering where this falls in the timeline. One of my "always-installs"!

**Comment by retorquere** [comment]
There really isn't a timeline. This one really shouldn't be hard but I'm starved for time right now. The PhD startup process is taking tons more time than I'd hoped, most of it dealing with non-research stuff like further funding acquisition and organizing interests of commercial partners attached to the over arching project.

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 12](https://github.com/retorquere/zotero-auto-index/releases/download/builds/zotero-better-bibtex-5.0.0.12.issue-8.xpi) ("circle").

**Comment by BenjaminHCCarr** [comment]
@retorquere was this build posted in the wrong place or yanked after a couple hours for a reason?

link is 404'ing after 6 hours.

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 17](https://github.com/retorquere/zotero-auto-index/releases/download/builds/zotero-auto-index-5.0.3.17.issue-8.xpi) ("ncu").

**Comment by retorquere** [comment]
The release scripts weren't properly generalized and still had BBT-specific stuff in them. The links now work.

**Comment by BenjaminHCCarr** [comment]
AH! Sorry to pester you re: timetable! but thanks for the build!

![Success!!!!!!!!!!!!](https://user-images.githubusercontent.com/8225968/36120647-e1842032-1011-11e8-9210-8ffac01aa668.png)

Success!!!!!!!!!!!!

**Comment by retorquere** [comment]
No worries. It's sometimes good to know these are still used, and little fixes like these are a welcome distraction sometimes.

**Comment by retorquere** [comment]
out now as 5.0.4. Debug builds update automatically, and 5.0.4 is just a rebranded 5.0.3.17. so you don't have to do anything.
